### ISSUE TITLE
I can't run the bot

### ISSUE THREAD

**Issue by pikopie** [Gigabars/FishHook#1]
Hi,

I was able to do steps 1 to 10 in the instructions.  But I was stuck at step no. 11.Run start.bat

After I clicked on start.bat inside the "Files" folder a cmd window opens up, and then the cmd window automatically closes in less than 1 second.  Please help.  Thx.

**Comment by Gigabars** [comment]
I'll be honest, this code is so old now I don't even remember what the heck I did to it, and this issue is almost 5 months old now, but another way you can start it is if you press Shift + Right in the files directory and then type node bot.js into whatever prompt comes up.
